# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - BooqeeGAP/development

pool:
  vmImage: "ubuntu-16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.9.1"
    displayName: "Install Node.js"

  - script: |
      npm install -g @angular/cli@9.0.3
      npm install @angular-devkit/build-angular
      npm install
      npm install -g increase-memory-limit
      node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration=default_production --build-optimizer
    displayName: "npm install and build"

  - task: CopyFiles@1
    inputs:
      sourceFolder: "dist/UserManagement"
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: UserManagement
